# Generated by Django 2.1.5 on 2019-03-03 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nrc',
            fields=[
                ('nrcCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nrcName', models.CharField(max_length=100)),
                ('bedCapacity', models.IntegerField(default=0)),
                ('bedAvailable', models.IntegerField(default=0)),
                ('waiting', models.IntegerField(default=0)),
                ('requested', models.IntegerField(default=0)),
                ('totalTreated', models.IntegerField(default=0)),
                ('totalSamFound', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.District')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('childName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('motherName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('tehsil', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isEdema', models.BooleanField(default=False)),
                ('isThinLimb', models.BooleanField(default=False)),
                ('isSwellingStomach', models.BooleanField(default=False)),
                ('isBrownHair', models.BooleanField(default=False)),
                ('isHygiene', models.BooleanField(default=False)),
                ('isFever', models.BooleanField(default=False)),
                ('isLossOfApetite', models.BooleanField(default=False)),
                ('umac', models.IntegerField(default=0)),
                ('nrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nrc')),
            ],
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('mailId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('isBlocked', models.BooleanField(default=False)),
                ('fakeCount', models.IntegerField(default=0)),
                ('successCount', models.IntegerField(default=0)),
                ('totalCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Referral')),
                ('updatedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False)),
                ('nrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nrc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='referral',
            name='refree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Refree'),
        ),
        migrations.AddField(
            model_name='division',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Division'),
        ),
    ]
