# Generated by Django 2.1.5 on 2019-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='isBrownHair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isEdema',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isFever',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isHygiene',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isLossOfApetite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isSwellingStomach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='isThinLimb',
            field=models.IntegerField(default=0),
        ),
    ]
