# Generated by Django 2.1.5 on 2019-03-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190303_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='isRural',
            field=models.IntegerField(default=1),
        ),
    ]
